### ISSUE TITLE
Alterar agenda para ter scroll infinito com os eventos como cards

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/mci#4]
- [x] Retirar seções da parte de baixo
- [x] Retirar imagem de destaque
- [x] Fazer scroll infinito com os cards
- [x] Retirar filtro local por localização

**Comment by fabiomontefuscolo** [comment]
@rafaelchavesfreitas @brunosmartin essa issue já era?

**Comment by rafaelchavesfreitas** [comment]
não foi feito scroll infinito nem cards, só alteramos o layout
