### ISSUE TITLE
Configurar envio de email pelo wordpress

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/mci#8]
preciso disso para para criação de usuários wordpress.

Acho que rola fazer como é feito no timtec, com mailgun e postfix.

Fábio, qq coisa me dá um toque que eu te mostro como faz.

**Comment by fabiomontefuscolo** [comment]
Tem que esperar eles transferirem o domínio ... também tem a opção de já deixar tudo pronto com um plugin wordpress.
